apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggyapp
  labels:
    app: buggyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggyapp
  template:
    metadata:
      labels:
        app: buggyapp
    spec:
      containers:
      - name: buggyapp
        image: ycrash/buggyapp:v1.0
        ports:
        - containerPort: 9010
        - containerPort: 8085
        volumeMounts:
        - name: ycrash-agent-config
          mountPath: "/opt/workspace/yc/agent/config.yaml"
          subPath: config.yaml
        resources:
          limits:
            memory: 1Gi
      volumes:
      - name: ycrash-agent-config
        secret:
          secretName: ycrash-agent-config
          items:
          - key: config.yaml
            path: config.yaml

