# Note this is combination of yc-deployment.yaml and yc-service.yaml. Alwasy update the image whenever we make a new yCrash releaseUploading
# Next upload this file in tier1app.com bucket and provid downloadable link to the users
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yc-web
  labels:
    app: yc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yc-web
  template:
    metadata:
      labels:
        app: yc-web
    spec:
      containers:
      - name: yc
        image: ycrash/ycrash:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: ycrash-license
          mountPath: "/opt/workspace/yc/license.lic"
          subPath: license.lic
      volumes:
      - name: ycrash-license
        secret:
          secretName: ycrash-license
          items:
          - key: license.lic
            path: license.lic
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yc-web
  name: yc-web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: yc-web
